name: C++ CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++ python3

    - name: Compile main.cpp
      run: g++ -Wall -Wextra main.cpp -o main

    - name: Start client-test
      run: g++ -Wall -Wextra echo_client.cpp -o client_echo

    - name: Run echo test
      run: 
        python3 echo_server.py &
        SERVER_PID=$!
        sleep 2
        ./echo_client
        CLIENT_EXIT=$?
        kill $SERVER_PID
        exit $CLIENT_EXIT

    